name: ok_route
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Caijinglong <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  yaml: 2.1.16
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
