name: ok_route_library
description: A new Flutter package project.
version: 0.1.1
author: caijinglong <cjl_spy@163.com>
homepage: https://github.com/CaiJingLong/ok_route/tree/master/ok_route_library

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
