name: ok_route
description: A sample command-line application.
version: 0.1.0
homepage: https://github.com/CaiJingLong/ok_route/tree/master/ok_route
author: Caijinglong <cjl_spy@163.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  yaml: ^2.1.16
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0

executables:
  ok_route: main
