name: ok_route
description: Use route with annotation. See document for how to use.
version: 0.1.4
homepage: https://github.com/CaiJingLong/ok_route/tree/master/ok_route
author: Caijinglong <cjl_spy@163.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  yaml: ^2.1.16

dev_dependencies:
  test: ^1.0.0

executables:
  ok_route: main
